/***
 *  Database of joint invariants.
 *
 *  Distributed under the terms of the GNU Lesser General Public License (L-GPL)
 *                  http://www.gnu.org/licenses/
 *
 *  This program is free software; you can redistribute it and/or modify
 *  it under the terms of the GNU Lesser General Public License as published by
 *  the Free Software Foundation; either version 2.1 of the License, or
 *  (at your option) any later version.
 *
 *  This program is distributed in the hope that it will be useful,
 *  but WITHOUT ANY WARRANTY; without even the implied warranty of
 *  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 *  GNU Lesser General Public License for more details.
 *
 *  You should have received a copy of the GNU Lesser General Public License
 *  along with this program; if not, write to the Free Software
 *  Foundation, Inc., 51 Franklin St, Fifth Floor, Boston, MA  02110-1301  USA
 *
 *  Copyright 2016 R. Lercier, C. Ritzenthaler & J. Sijsling
 */

S8S4Cov :=  [
rec<recformat<U, V, level, degree, order> | /* #0 : v */
		 U := {* 0 *},
		 V := {* *},
		 level := 0,
		 degree := 1,
		 order := 4>,
rec<recformat<U, V, level, degree, order> |  /* #1 : f */
		 U := {* 1 *},
		 V := {* *},
		 level := 0,
		 degree := 1,
		 order := 8>,
rec<recformat<U, V, level, degree, order> | /* #2 : f2 */
		 U := {* 1 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 2,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #3 : f3 */
		 U := {* 1 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 2,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #4 : f4 */
		 U := {* 1 *},
		 V := {* 1 *},
		 level := 4,
		 degree := 2,
		 order := 8>,
rec<recformat<U, V, level, degree, order> | /* #5 : f5 */
		 U := {* 1 *},
		 V := {* 1 *},
		 level := 2,
		 degree := 2,
		 order := 12>,
rec<recformat<U, V, level, degree, order> | /* #6 : f6 */
		 U := {* 4 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 3,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #7 : f7 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 3,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #8 : f8 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 3,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #9 : f9 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 3,
		 order := 8>,
rec<recformat<U, V, level, degree, order> | /* #10 : f10 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 5,
		 degree := 3,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #11 : f11 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 4,
		 degree := 3,
		 order := 12>,
rec<recformat<U, V, level, degree, order> | /* #12 : f12 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 3,
		 degree := 3,
		 order := 14>,
rec<recformat<U, V, level, degree, order> | /* #13 : f13 */
		 U := {* 5 *},
		 V := {* 1 *},
		 level := 1,
		 degree := 3,
		 order := 18>,
rec<recformat<U, V, level, degree, order> | /* #14 : f14 */
		 U := {* 9 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 4,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #15 : f15 */
		 U := {* 11 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 4,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #16 : f16 */
		 U := {* 10 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 4,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #17 : f17 */
		 U := {* 12 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 4,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #18 : f18 */
		 U := {* 12 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 4,
		 order := 8>,
rec<recformat<U, V, level, degree, order> | /* #19 : f19 */
		 U := {* 13 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 4,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #20 : f20 */
		 U := {* 12 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 4,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #21 : f21 */
		 U := {* 13 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 4,
		 order := 12>,
rec<recformat<U, V, level, degree, order> | /* #22 : f22 */
		 U := {* 13 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 4,
		 order := 14>,
rec<recformat<U, V, level, degree, order> | /* #23 : f23 */
		 U := {* 13 *},
		 V := {* 1 *},
		 level := 4,
		 degree := 4,
		 order := 18>,
rec<recformat<U, V, level, degree, order> | /* #24 : f24 */
		 U := {* 3^^2 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #25 : f25 */
		 U := {* 20 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 5,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #26 : f26 */
		 U := {* 21 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 5,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #27 : f27 */
		 U := {* 20 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 5,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #28 : f28 */
		 U := {* 22 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 5,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #29 : f29 */
		 U := {* 21 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 5,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #30 : f30 */
		 U := {* 22 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 5,
		 order := 8>,
rec<recformat<U, V, level, degree, order> | /* #31 : f31 */
		 U := {* 23 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 5,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #32 : f32 */
		 U := {* 22 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 5,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #33 : f33 */
		 U := {* 21 *},
		 V := {* 1 *},
		 level := 5,
		 degree := 5,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #34 : f34 */
		 U := {* 23 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 5,
		 order := 14>,
rec<recformat<U, V, level, degree, order> | /* #35 : f35 */
		 U := {* 3, 7 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #36 : f36 */
		 U := {* 33 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 6,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #37 : f37 */
		 U := {* 33 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 6,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #38 : f38 */
		 U := {* 32 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 6,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #39 : f39 */
		 U := {* 34 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 6,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #40 : f40 */
		 U := {* 33 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 6,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #41 : f41 */
		 U := {* 32 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 6,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #42 : f42 */
		 U := {* 34 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 6,
		 order := 8>,
rec<recformat<U, V, level, degree, order> | /* #43 : f43 */
		 U := {* 34 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 6,
		 order := 10>,
rec<recformat<U, V, level, degree, order> | /* #44 : f44 */
		 U := {* 7^^2 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #45 : f45 */
		 U := {* 43 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 7,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #46 : f46 */
		 U := {* 42 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 7,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #47 : f47 */
		 U := {* 43 *},
		 V := {* 1 *},
		 level := 7,
		 degree := 7,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #48 : f48 */
		 U := {* 42 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 7,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #49 : f49 */
		 U := {* 43 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 7,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #50 : f50 */
		 U := {* 42 *},
		 V := {* 1 *},
		 level := 5,
		 degree := 7,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #51 : f51 */
		 U := {* 41 *},
		 V := {* 1 *},
		 level := 4,
		 degree := 7,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #52 : f52 */
		 U := {* 7, 16 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #53 : f53 */
		 U := {* 51 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 8,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #54 : f54 */
		 U := {* 50 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 8,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #55 : f55 */
		 U := {* 51 *},
		 V := {* 1 *},
		 level := 5,
		 degree := 8,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #56 : f56 */
		 U := {* 50 *},
		 V := {* 1 *},
		 level := 5,
		 degree := 8,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #57 : f57 */
		 U := {* 51 *},
		 V := {* 1 *},
		 level := 4,
		 degree := 8,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #58 : f58 */
		 U := {* 50 *},
		 V := {* 1 *},
		 level := 4,
		 degree := 8,
		 order := 6>,
rec<recformat<U, V, level, degree, order> | /* #59 : f59 */
		 U := {* 15, 16 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 9,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #60 : f60 */
		 U := {* 58 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 9,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #61 : f61 */
		 U := {* 57 *},
		 V := {* 1 *},
		 level := 6,
		 degree := 9,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #62 : f62 */
		 U := {* 16, 17 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 9,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #63 : f63 */
		 U := {* 58 *},
		 V := {* 1 *},
		 level := 5,
		 degree := 9,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #64 : f64 */
		 U := {* 17, 25 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 10,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #65 : f65 */
		 U := {* 17, 27 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 10,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #66 : f66 */
		 U := {* 17, 26 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 10,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #67 : f67 */
		 U := {* 27, 29 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 11,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #68 : f68 */
		 U := {* 27, 28 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 11,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #69 : f69 */
		 U := {* 29, 38 *},
		 V := {* 1 *},
		 level := 8,
		 degree := 12,
		 order := 2>,
rec<recformat<U, V, level, degree, order> | /* #70 : v1 */
		 U := {* 0 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 2,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #71 : v2 */
		 U := {* 0 *},
		 V := {* 0 *},
		 level := 2,
		 degree := 2,
		 order := 4>,
rec<recformat<U, V, level, degree, order> | /* #72 : v3 */
		 U := {* 71 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 3,
		 order := 0>,
rec<recformat<U, V, level, degree, order> | /* #73 : v4 */
		 U := {* 71 *},
		 V := {* 0 *},
		 level := 1,
		 degree := 3,
		 order := 6>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 3 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 3,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 1 *},
		 V := {* 0^^2 *},
		 level := 8,
		 degree := 3,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 1 *},
		 V := {* 0, 71 *},
		 level := 8,
		 degree := 4,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 4 *},
		 V := {* 0^^2 *},
		 level := 8,
		 degree := 4,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 3 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 4,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 7 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 4,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 1 *},
		 V := {* 71^^2 *},
		 level := 8,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 4 *},
		 V := {* 0, 71 *},
		 level := 8,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 5 *},
		 V := {* 0^^3 *},
		 level := 12,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 7 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 9 *},
		 V := {* 0^^2 *},
		 level := 8,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 15 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 16 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 5,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 4 *},
		 V := {* 71^^2 *},
		 level := 8,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 5 *},
		 V := {* 0^^2, 71 *},
		 level := 12,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 11 *},
		 V := {* 0^^3 *},
		 level := 12,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 9 *},
		 V := {* 0, 71 *},
		 level := 8,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 8 *},
		 V := {* 73 *},
		 level := 6,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 15 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 18 *},
		 V := {* 0^^2 *},
		 level := 8,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 16 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 26 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 27 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 6,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 5 *},
		 V := {* 0, 71^^2 *},
		 level := 12,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 10 *},
		 V := {* 0, 73 *},
		 level := 10,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 11 *},
		 V := {* 0^^2, 71 *},
		 level := 12,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 18 *},
		 V := {* 0, 71 *},
		 level := 8,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 17 *},
		 V := {* 73 *},
		 level := 6,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 21 *},
		 V := {* 0^^3 *},
		 level := 12,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 30 *},
		 V := {* 0^^2 *},
		 level := 8,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 27 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 26 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 37 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 38 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 7,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 47 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 48 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 37 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 38 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 42 *},
		 V := {* 0^^2 *},
		 level := 8,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 29 *},
		 V := {* 73 *},
		 level := 6,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 30 *},
		 V := {* 0, 71 *},
		 level := 8,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 20 *},
		 V := {* 0, 73 *},
		 level := 10,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 21 *},
		 V := {* 0^^2, 71 *},
		 level := 12,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 11 *},
		 V := {* 0, 71^^2 *},
		 level := 12,
		 degree := 8,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 8^^2 *},
		 V := {* 0^^3 *},
		 level := 12,
		 degree := 9,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 48 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 9,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 47 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 9,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 55 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 9,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 56 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 9,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 56 *},
		 V := {* 71 *},
		 level := 4,
		 degree := 10,
		 order := 0>,
rec<recformat<U, V, level, degree, order> |
		 U := {* 63 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 10,
		 order := 0>,
/*
rec<recformat<U, V, level, degree, order> |
		 U := {* 63 *}, V := {* 71 *}, // Inv. lié, à voir avec marc ?
		 level := 4,
		 degree := 11,
		 order := 0>,
*/
rec<recformat<U, V, level, degree, order> |
		 U := {* 25^^2 *},
		 V := {* 0 *},
		 level := 4,
		 degree := 11,
		 order := 0>
];
